apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

      - name: backend

        image: asia-south1-docker.pkg.dev/gke-demo-project-497408/demo-repo/backend:v1

        ports:

        - containerPort: 3000

        volumeMounts:

        - name: gcp

          mountPath: /app/key

      volumes:

      - name: gcp

        secret:

          secretName: gcp-secret
