apiVersion: apps/v1

kind: Deployment

metadata:
  name: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:

    metadata:
      labels:
        app: frontend

    spec:

      containers:

      - name: frontend

        image: asia-south1-docker.pkg.dev/gke-demo-project-497408/demo-repo/frontend:v1

        ports:

        - containerPort: 80
